export enum FlebiteClassification {
  CHEMICAL_FLEBITE = 'FLEBITE QUÍMICA',
  MECHANICAL_FLEBITE = 'FLEBITE MECÂNICA',
  INFECTIOUS_FLEBITE = 'FLEBITE INFECCIOSA',
  FLEBITE_POST_INFUSIONAL = 'FLEBITE PÓS-INFUSIONAL',
  UNCLASSIFIED = 'NÃO CLASSIFICÁVEL',
}

export enum FlebiteRiskLevel {
  LEVEL_0 = 'GRAU 0 - SEM SINAIS CLÍNICOS',
  LEVEL_1 = 'GRAU 1 - ERITEMA, COM OU SEM DOR LOCAL',
  LEVEL_2 = 'GRAU 2 - DOR, ERITEMA E OU EDEMA',
  LEVEL_3 = 'GRAU 3 - GRAU 2 + ENDURECIMENTO CORDÃO FIBROSO PALPÁVEL',
}
