export enum ErrorCategory {
  ADMINISTRATION = 'ADMINISTRAÇÃO',
  ETHICAL_CONDUCT = 'CONDUTA ÉTICA',
  DISPENSATION = 'DISPENSAÇÃO',
  MEDICATION_LEAKAGE = 'EXTRAVASAMENTO DE MEDICAÇÃO',
  PRESCRIPTION = 'PRESCRIÇÃO',
  ADVERSE_REACTION = 'REAÇÃO ADVERSA',
  TECHNICAL_COMPLAINT = 'QUEIXA TÉCNICA',
  UNCLASSIFIABLE = 'NÃO CLASSIFICÁVEL',
}
